script: ./.travis/build
before_install:
- git submodule update --init --recursive
compiler:
- gcc
notifications:
  email:
  - francois.keith@gmail.com
branches:
  only:
  - master
  - travis
  - catkin
  - catkin_robohow_2
language: cpp
matrix:
  allow_failures:
  - compiler: clang
